[package]
name = "space_invaders"
version = "0.1.0"
authors = ["Pearce Keesling <keeslinp@gmail.com>"]

[dependencies]
ggez = "0.3"
uuid = { version = "0.5", features = ["serde", "v4"] }
rand = "0.3"
